### ISSUE TITLE
Online editor & preview

### ISSUE THREAD

**Issue by srid** [tfausak/haskell-knowledge-base#11]
Via https://www.cerveau.app and provide free accounts to contributors.

**Comment by srid** [comment]
Cerveau is a GitHub App, and GitHub Apps can only be installed on either personal GitHub account or on an organization account (of which one is a member of).

So I (or anybody else other than the repo owner) do not have permissions to install it on tfausak/haskell-knowledge-base, so won't be able to edit notes online. However, if we move this repo to an organization - then all members of that organization (depending on repo/team permissions) would be able to edit this KB using the Cerveau editor. 

I thought it would minimize initial friction if the Haskell KB can be edited directly in the browser with live preview (what Cerveau provides). Thoughts @tfausak ?

Cerveau [demo here](https://ipfs.io/ipfs/QmbBG3KKDFFE1VdyJ5FQc7Zkd85zcxXrwA73M9NeAeWkYX?filename=2020%20cerveau-live-preview.webm).

**Comment by tfausak** [comment]
Sounds good to me! What would it take to get this set up? `@haskell-knowledge-base` appears to be available on GitHub, so it could be an organization. It would be nice to make this available under the `@haskell` organization, but I have no idea what that requires.

**Comment by srid** [comment]
Ah, I just realized that Cerveau supports neuron v1 only, which doesn't support sub directories. So we can't use it for this KB.

In any case, when this KB gets more content and/or get official blessing in haskell.org it might make sense to move it to @haskell org, but it is not critical right now. 

By the way, I have a prototype example of a KB site based on [emabook](https://github.com/srid/emabook) (which unlike neuron supports fully customizable HTML layout via Heist engine) here: https://haskell-kb.srid.ca/ ... it still need to address some bugs, support a few features: graph view, search queries, embeds, etc. - but the goal is to have a fully customizable publishing mechanism for markdown notes, with Obsidian-friendly feature set. I'm using this KB as a 'test bed' to develop emabook (which is going to be next-gen neuron).
