### ISSUE TITLE
Replace manual listing with queries

### ISSUE THREAD

**Issue by srid** [tfausak/haskell-knowledge-base#12]
In many "index" notes ([example](https://github.com/tfausak/haskell-knowledge-base/blob/2eac4fd5f9cf67811239d22e6f1f0b61de4a15f2/Concepts.md)) we manually list the directory contents using Markdown lists. Obsidian has support for queries. For example adding a code block with language "query" and contents `path:"Daily Notes/2020-07"` will list the notes under that month folder. 

https://help.obsidian.md/Plugins/Search

They say the "embed" feature is not supported by Obsidian Publish. Once it does we could just switch to using that. I plan to add support for Obsidian style queries in [emanote](https://github.com/srid/emanote) (which has now replaced neuron for this KB).

**Comment by srid** [comment]
More about this feature: https://www.youtube.com/watch?v=hUCMGw8uMRg&t=74s

**Comment by tfausak** [comment]
Clearly my interest in this project has waned. I'm not opposed to this per se, but I'm going to close the issue since I'm not really working on this anymore.
